name: DungeonRealms
main: net.dungeonrealms.DungeonRealms
version: 1.0
authors: [xFinityPro, Proxying, Xwaffle, apollosoftware]
website: http://www.dungeonrealms.net
depend: [BountifulAPI, WorldGuard, BossBarAPI, ProtocolLib]
description: The new dungeonrealms!