name: DungeonRealms-Optimized
main: net.dungeonrealms.DungeonRealms
verson: 1.0
authors: [xFinityPro, Proxying, Xwaffle]
website: http://www.dungeonrealms.net
depend: [BountifulAPI, WorldGuard]
description: The new dungeonrealms!